{% set name = "kinship-read" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/GuntherLab/READv2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4ca327cdc192c4f90b43c55100cc49786fdd4e916cb160fa4e05b97258a2f64a

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}


requirements:
  host:
    - pip
    - python
  run:
    - python >=3.7
    - numpy
    - pandas
    - matplotlib-base
    - plinkio

test:
  commands:
    - kinship-read --help

about:
  home: https://github.com/GuntherLab/READv2
  license: GPL-3.0-only
  license_file: LICENSE
  summary: "Relationship Estimation from Ancient DNA version 2 (READv2)"
  doc_url: https://github.com/GuntherLab/READv2?tab=readme-ov-file

extra:
  recipe-maintainers:
    - SonofLastPanda
